Models/Calisanlar.cs
using System.ComponentModel.DataAnnotations;

namespace MicroYazilim.Models
{
    public class Calisanlar
    {
        [Key]
        public int id { get; set; }
        public String Baslik { get; set; }
        public String Icerik   { get; set; }
        public String Resim { get; set; }
    }
}

Models/Data/Context.cs
using Microsoft.EntityFrameworkCore;

namespace MicroYazilim.Models.Data
{
    public class Context:DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "server=DESKTOP-V7NEGGO\\SQLEXPRESS;database=MicroYazilim;integrated security=true;" +
                "TrustServercertificate=True;"
                );
        }
        public DbSet<Calisanlar> Calisanlar { get; set; }
        public DbSet<Hizmetler> Hizmetler { get; set; }
        public DbSet<Iletisim> Iletisim { get; set; }
        public DbSet<Referanslar> Referanslar { get; set; }
        public DbSet<Teklif> Teklifs { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace MicroYazilim.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Hizmetler.cs
using System.ComponentModel.DataAnnotations;

namespace MicroYazilim.Models
{
    public class Hizmetler
    {
        [Key]
        public int id { get; set; }
        public String Baslik { get; set; }
        public String Icerik { get; set; }
        public String Resim { get; set; }
    }
}

Models/Iletisim.cs
using System.ComponentModel.DataAnnotations;

namespace MicroYazilim.Models
{
    public class Iletisim
    {
        [Key]
        public int id { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public string Konu { get; set; }
        public String Mesaj { get; set; }
    }
}

Models/Referanslar.cs
using System.ComponentModel.DataAnnotations;

namespace MicroYazilim.Models
{
    public class Referanslar
    {
        [Key]
        public int id { get; set; }
        public String Baslik { get; set; }
        public String Icerik { get; set; }
        public String Resim { get; set; }
    }
}

Models/Teklif.cs
using System.ComponentModel.DataAnnotations;

namespace MicroYazilim.Models
{
    public class Teklif
    {
        [Key]
        public int id { get; set; }
        public String AdSoyad { get; set; }
        public String  FirmaIsmi { get; set; }
        public String Email { get; set; }
        public int Telefon { get; set; }
        public String HizmetTuru { get; set; }
    }
}

Controllers/HizmetController.cs
using Microsoft.AspNetCore.Mvc;
using MicroYazilim.BusinessLogic.HizmetLogic.Interfaces;
using MicroYazilim.Models.Data;

namespace MicroYazilim.Controllers
{
    public class HizmetController : Controller
    {
        private readonly IHizmetRepository _hizmetRepository;
        public HizmetController(IHizmetRepository hizmetRepository)
        {
            _hizmetRepository = hizmetRepository;
        }
        //Context context=new Context();
        public IActionResult Index()
        {
            //var hzm=context.Hizmetler.ToList();
            //return View(hzm);
            var hzm = _hizmetRepository.GetHizmetler();
            return View(hzm);
        }
        public IActionResult Details(int id) { 
           var detay= _hizmetRepository.HizmetDetails(id);
            return View(detay);
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MicroYazilim.BusinessLogic.HizmetLogic.Interfaces;
using MicroYazilim.Models;
using System.Diagnostics;

namespace MicroYazilim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHizmetRepository _hizmetRepository;
        public HomeController(ILogger<HomeController> logger,IHizmetRepository   hizmetRepository)
        {
            _hizmetRepository = hizmetRepository;
            _logger = logger;
        }

        public IActionResult Index()
        {
            var hizmetler=_hizmetRepository.GetHizmetler();
            return View(hizmetler);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/IletisimController.cs
using Microsoft.AspNetCore.Mvc;
using MicroYazilim.Models;
using MicroYazilim.Models.Data;

namespace MicroYazilim.Controllers
{
    public class IletisimController : Controller
    {
        private readonly Context context=new Context();
        public IActionResult Index() {
            return View();
        }
        [HttpGet]
        public IActionResult IletisimBilgileri()
        {
            return View();
        }
        [HttpPost]
        public IActionResult IletisimBilgileri(Iletisim ıletisim)
        {
            context.Iletisim.Add(ıletisim);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Controllers/ReferansController.cs
using Microsoft.AspNetCore.Mvc;
using MicroYazilim.BusinessLogic.ReferansLogic.Interfaces;

namespace MicroYazilim.Controllers
{
    public class ReferansController : Controller
    {
        private readonly IReferansRepo referansRepo;
        public ReferansController(IReferansRepo _referansRepo)
        {
            referansRepo = _referansRepo;
        }
        public IActionResult GetReferans()
        {
            var rfr=referansRepo.GetReferanslar();
            return View(rfr);
        }
        public IActionResult Details(int id) { 
           var detay=referansRepo.ReferansDetails(id);
            return View(detay);
        }
    }
}

Controllers/TeklifController.cs
using Microsoft.AspNetCore.Mvc;
using MicroYazilim.Models;
using MicroYazilim.Models.Data;

namespace MicroYazilim.Controllers
{
    public class TeklifController : Controller
    {
        private readonly Context context=new Context(); 
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult TeklifAl() { 
          return View();
        }
        [HttpPost]
        public IActionResult TeklifAl(Teklif teklif) {
            context.Teklifs.Add(teklif);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Hizmet/Details.cshtml
@model MicroYazilim.Models.Hizmetler
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
@Html.DisplayFor(x=>x.Baslik)<br />
@Html.DisplayFor(x=>x.Icerik)<br />
<img src="@Html.DisplayFor(x=>x.Resim)" width="900px" height="700px">


Views/Hizmet/Index.cshtml
@model List<MicroYazilim.Models.Hizmetler>
<link href="~/css/hizmet.css" rel="stylesheet" />
<div class="main">
            @foreach (var x in Model)
            {
                <div class="icerik">
                  @x.Baslik
                  <a asp-controller="Hizmet" asp-action="Details" asp-route-id="@x.id">
                    <img src="@x.Resim" width="300px" height="300px">
                  </a>
                </div>
            }
</div>
        

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<MicroYazilim.Models.Hizmetler>
<link href="~/css/fiyatlandirma.css" rel="stylesheet" />
<link href="~/css/hizmet.css" rel="stylesheet" />
<link href="~/css/ozet.css" rel="stylesheet" />
<div class="main">
    @foreach (var x in Model)
    {
        <div class="icerik">
            @x.Baslik
            <a asp-controller="Hizmet" asp-action="Details" asp-route-id="@x.id">
                <img src="@x.Resim" width="300px" height="300px">
            </a>
        </div>
    }
</div>

<div class="main2">
    <div class="fiyatlandirma">
        Fiyatlandırma
    </div>
    <div class="icerik2">
        <p>Web Yazılım</p>
        Uzman ekiplerimiz sayesinde titizlikle yürüttüğümüz projelerimizde genel olarak ücretlendirme politikamız
        belli başlı konulara göre belirlenmektedir. Bu hususlar genel olarak; görev alacak personel sayısı,
        projenin tamamlanma süresi, özel ek hizmetlerin bulunup bulunmadığı, projenin zorluk seviyesi ve sayfa
        sayısı örnek olarak verilebilmektedir. Proje fiyatlandırması konusunda  
        yürütülebilmesi için CodeLab müşteri hizmetleriyle iletişime geçmeniz gerekmektedir.
        Yaptığımız modul başına 8000tl alıyoruz.

    </div>
    <div class="icerik2">
        <p>App geliştirme</p>
        İhtiyaçlarınız doğrultusunda ve beklentileriniz kapsamında detaylı planlama listelerinin oluşturulması
        Listelenen planların projelendirme süreçlerinin oluşturulması
        İstenilen özellikler ve kapsamlar içerisinde uzman ekiplerimiz tarafından gerekli yazılım süreç tasarımlarının 
        ve uygulama iç dizayn proseslerinin oluşturulması
        Yaptığımız modul başına 10000tl alıyoruz.
    </div>
    <div class="icerik2">
        <p>ERP geliştirme</p>Şirket kültürümüz olarak belirlediğimiz en iyi ve kaliteli hizmet anlayışımızla
        yazılım sektöründe yola çıktığımız takım arkadaşlarımız da dahil tüm CodeLab ekibi olarak şeffaflık, 
        adil, güçlü iletişim, yüksek müşteri memnuniyeti, sürekli gelişim ve sürdürülebilirlik stratejileri 
        doğrultusunda adım atmaktayız. Bu aldığımız doğru kararlar neticesinde günümüzde görülmektedir ki CodeLab
        sektörün öncüleri arasında yerini almış bulunmaktadır
        Yaptığımız modul başına 12000tl alıyoruz.

    </div>
    <div class="icerik2">
        <p>Otomasyon geliştirme</p>
        Özel yazılım alanında vermiş olduğumuz ücretlendirme politikalarımız bazı ana ve alt kriterlere göre farklılık göstermektedir. Bu kriterler başlıca şu şekilde verilebilmektedir;

        Proje büyüklüğü
        Projenin kapsamı
        Projede görev alacak uzman sayısı
        Tahmini teslimat süresi
        Projede kullanılacak sayfa sayısı
        Yaptığımız modul başına 15000tl alıyoruz.

    </div>
</div>
<div class="ozet-main">
    <div class="parca">
        <p>112+</p>
        Mutlu müşteri
    </div>
    <div class="parca">
        <p>138+</p>
        Aktif iş
    </div>
    <div class="parca">
        <p>6+</p>
        Aktif tecrübe
    </div>
</div>

Views/Iletisim/IletisimBilgileri.cshtml
@model MicroYazilim.Models.Iletisim
@{
    ViewData["Title"] = "IletisimBilgileri";
}

<h1>IletisimBilgileri</h1>
<form method="post">
    <b>Ad</b>
    @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
    <br />
    <b>Firma İsmi</b>
    @Html.TextBoxFor(x => x.SoyAd, new { @class = "form-control" })
    <br />
    <b>Email</b>
    @Html.TextBoxFor(x => x.Konu, new { @class = "form-control" })
    <br />
    <b>Telefon</b>
    @Html.TextBoxFor(x => x.Mesaj, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Gönder</button>
</form>


Views/Iletisim/Index.cshtml

@{
    ViewData["Title"] = "Index";
}

<h1>İletişim</h1>
<h1>
    Bilgileriniz alınmıştır .En kısa sürede size geri dönüş yapılacaktır.
    Teşekkürler...
</h1>


Views/Referans/Details.cshtml
@{
    ViewData["Title"] = "ReferansDetails";
}

<h1>Referans Detay</h1>

@model MicroYazilim.Models.Referanslar
@Html.DisplayFor(x => x.Baslik)
<br />
@Html.DisplayFor(x => x.Icerik)
<br />
<img src="@Html.DisplayFor(x=>x.Resim)" width="900px" height="700px">


Views/Referans/GetReferans.cshtml
@model List<MicroYazilim.Models.Referanslar>
@{
    ViewData["Title"] = "GetReferans";
}

<h1>GetReferans</h1>
<link href="~/css/hizmet.css" rel="stylesheet" />
<div class="main">
    @foreach (var x in Model)
    {
        <div class="icerik">
            @x.Baslik
            <a asp-controller="Referans" asp-action="Details" asp-route-id="@x.id">
                <img src="@x.Resim" width="300px" height="300px">
            </a>
        </div>
    }
</div>


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MicroYazilim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MicroYazilim.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MicroYazilim</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasyfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hizmet" asp-action="Index">Hizmetler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Referans" asp-action="GetReferans">Portfolyo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teklif" asp-action="TeklifAl">Teklif Al</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Iletisim" asp-action="IletisimBilgileri">İletişim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Hakkımızda</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MicroYazilim - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Teklif/Index.cshtml

@{
    ViewData["Title"] = "Index";
}

<h1>Teklif Sonuç</h1>
<h1>Bilgileriniz alınmıştır .En kısa sürede size geri dönüş yapılacaktır.
Teşekkürler...</h1>


Views/Teklif/TeklifAl.cshtml
@model MicroYazilim.Models.Teklif
@{
    ViewData["Title"] = "TeklifAl";
}
<link href="c:\users\asus\source\repos\microyazilim\microyazilim\wwwroot\css\teklif.css" rel="stylesheet" />
<h1>TeklifAl</h1>
<div class="teklifmain">
  <form method="post">
    <b>Ad Soyad</b>
    @Html.TextBoxFor(x => x.AdSoyad, new { @class = "form-control" })
    <br />
    <b>Firma İsmi</b>
    @Html.TextBoxFor(x => x.FirmaIsmi, new { @class = "form-control" })
    <br />
    <b>Email</b>
    @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
    <br />
    <b>Telefon</b>
    @Html.TextBoxFor(x => x.Telefon, new { @class = "form-control" })
    <br />
    <b>Hizmet Türü</b>
    @Html.TextBoxFor(x => x.HizmetTuru, new { @class = "form-control" })
    <button class="btn btn-info">Teklif Al</button>
  </form>
</div>